#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XamarinATime.Resource", IsApplication=true)]

namespace XamarinATime
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int btn_blue = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int btn_grey = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int btn_white = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06002c
			public const int About = 2131099692;
			
			// aapt resource value: 0x7f06002b
			public const int Configuration = 2131099691;
			
			// aapt resource value: 0x7f06002f
			public const int ScrollView01 = 2131099695;
			
			// aapt resource value: 0x7f060000
			public const int ScrollView_about = 2131099648;
			
			// aapt resource value: 0x7f060012
			public const int ScrollView_configuration = 2131099666;
			
			// aapt resource value: 0x7f060024
			public const int about_atime = 2131099684;
			
			// aapt resource value: 0x7f06002a
			public const int button_1 = 2131099690;
			
			// aapt resource value: 0x7f060010
			public const int button_2 = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int configuration_layout = 2131099665;
			
			// aapt resource value: 0x7f06002e
			public const int configure_text = 2131099694;
			
			// aapt resource value: 0x7f060020
			public const int current_date = 2131099680;
			
			// aapt resource value: 0x7f06001f
			public const int current_loc = 2131099679;
			
			// aapt resource value: 0x7f060021
			public const int datePicker_1 = 2131099681;
			
			// aapt resource value: 0x7f060022
			public const int findMyLoc = 2131099682;
			
			// aapt resource value: 0x7f060017
			public const int input_latitude = 2131099671;
			
			// aapt resource value: 0x7f06001a
			public const int input_longitude = 2131099674;
			
			// aapt resource value: 0x7f06001d
			public const int input_offset = 2131099677;
			
			// aapt resource value: 0x7f060001
			public const int layout_root = 2131099649;
			
			// aapt resource value: 0x7f060015
			public const int linearLayout1 = 2131099669;
			
			// aapt resource value: 0x7f060018
			public const int linearLayout2 = 2131099672;
			
			// aapt resource value: 0x7f06001b
			public const int linearLayout3 = 2131099675;
			
			// aapt resource value: 0x7f060013
			public const int linearLayout_bottombutton = 2131099667;
			
			// aapt resource value: 0x7f06001e
			public const int linearLayout_middlebutton = 2131099678;
			
			// aapt resource value: 0x7f060030
			public const int linear_child = 2131099696;
			
			// aapt resource value: 0x7f060014
			public const int scrollable_layout = 2131099668;
			
			// aapt resource value: 0x7f060023
			public const int submit = 2131099683;
			
			// aapt resource value: 0x7f060002
			public const int text_1 = 2131099650;
			
			// aapt resource value: 0x7f06000b
			public const int text_10 = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int text_11 = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int text_12 = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int text_13 = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int text_14 = 2131099663;
			
			// aapt resource value: 0x7f060003
			public const int text_2 = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int text_3 = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int text_4 = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int text_5 = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int text_6 = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int text_7 = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int text_8 = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int text_9 = 2131099658;
			
			// aapt resource value: 0x7f060050
			public const int text_belowright_1 = 2131099728;
			
			// aapt resource value: 0x7f060051
			public const int text_belowright_2 = 2131099729;
			
			// aapt resource value: 0x7f060052
			public const int text_belowright_3 = 2131099730;
			
			// aapt resource value: 0x7f060053
			public const int text_belowright_4 = 2131099731;
			
			// aapt resource value: 0x7f060054
			public const int text_belowright_5 = 2131099732;
			
			// aapt resource value: 0x7f060055
			public const int text_belowright_6 = 2131099733;
			
			// aapt resource value: 0x7f060056
			public const int text_belowright_7 = 2131099734;
			
			// aapt resource value: 0x7f060057
			public const int text_belowright_8 = 2131099735;
			
			// aapt resource value: 0x7f060058
			public const int text_belowright_9 = 2131099736;
			
			// aapt resource value: 0x7f060027
			public const int text_detail3 = 2131099687;
			
			// aapt resource value: 0x7f060028
			public const int text_detail4 = 2131099688;
			
			// aapt resource value: 0x7f060029
			public const int text_detail5 = 2131099689;
			
			// aapt resource value: 0x7f060025
			public const int text_first = 2131099685;
			
			// aapt resource value: 0x7f060032
			public const int text_lastnight_1 = 2131099698;
			
			// aapt resource value: 0x7f060033
			public const int text_lastnight_2 = 2131099699;
			
			// aapt resource value: 0x7f060034
			public const int text_lastnight_3 = 2131099700;
			
			// aapt resource value: 0x7f060035
			public const int text_lastnight_4 = 2131099701;
			
			// aapt resource value: 0x7f060036
			public const int text_lastnight_5 = 2131099702;
			
			// aapt resource value: 0x7f060037
			public const int text_lastnight_6 = 2131099703;
			
			// aapt resource value: 0x7f060038
			public const int text_lastnight_7 = 2131099704;
			
			// aapt resource value: 0x7f060039
			public const int text_lastnight_8 = 2131099705;
			
			// aapt resource value: 0x7f06003a
			public const int text_lastnight_9 = 2131099706;
			
			// aapt resource value: 0x7f060016
			public const int text_latitude = 2131099670;
			
			// aapt resource value: 0x7f060019
			public const int text_longitude = 2131099673;
			
			// aapt resource value: 0x7f060026
			public const int text_second = 2131099686;
			
			// aapt resource value: 0x7f06001c
			public const int text_timeOffset = 2131099676;
			
			// aapt resource value: 0x7f06003c
			public const int text_today_1 = 2131099708;
			
			// aapt resource value: 0x7f06003d
			public const int text_today_2 = 2131099709;
			
			// aapt resource value: 0x7f06003e
			public const int text_today_3 = 2131099710;
			
			// aapt resource value: 0x7f06003f
			public const int text_today_4 = 2131099711;
			
			// aapt resource value: 0x7f060040
			public const int text_today_5 = 2131099712;
			
			// aapt resource value: 0x7f060041
			public const int text_today_6 = 2131099713;
			
			// aapt resource value: 0x7f060042
			public const int text_today_7 = 2131099714;
			
			// aapt resource value: 0x7f060043
			public const int text_today_8 = 2131099715;
			
			// aapt resource value: 0x7f060044
			public const int text_today_9 = 2131099716;
			
			// aapt resource value: 0x7f060046
			public const int text_tonight_1 = 2131099718;
			
			// aapt resource value: 0x7f060047
			public const int text_tonight_2 = 2131099719;
			
			// aapt resource value: 0x7f060048
			public const int text_tonight_3 = 2131099720;
			
			// aapt resource value: 0x7f060049
			public const int text_tonight_4 = 2131099721;
			
			// aapt resource value: 0x7f06004a
			public const int text_tonight_5 = 2131099722;
			
			// aapt resource value: 0x7f06004b
			public const int text_tonight_6 = 2131099723;
			
			// aapt resource value: 0x7f06004c
			public const int text_tonight_7 = 2131099724;
			
			// aapt resource value: 0x7f06004d
			public const int text_tonight_8 = 2131099725;
			
			// aapt resource value: 0x7f06004e
			public const int text_tonight_9 = 2131099726;
			
			// aapt resource value: 0x7f06002d
			public const int timeDisplay = 2131099693;
			
			// aapt resource value: 0x7f06003b
			public const int widget32 = 2131099707;
			
			// aapt resource value: 0x7f060045
			public const int widget33 = 2131099717;
			
			// aapt resource value: 0x7f060031
			public const int widget34 = 2131099697;
			
			// aapt resource value: 0x7f06004f
			public const int widget35 = 2131099727;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int About = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int configuration = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int FindMyLocation = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int AppTheme = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int ButtonCD = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int ButtonCL = 2131034115;
			
			// aapt resource value: 0x7f050007
			public const int ButtonConfiguration = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int ButtonHelp = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int ButtonOkay = 2131034118;
			
			// aapt resource value: 0x7f050001
			public const int ButtonReset = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int ButtonSubmit = 2131034114;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
